config {
  type: "assertion",
  description: "Raises an error if any event anomalies exist (alerts present)",
  dependencies: ["event_check_anomalies","event_monitoring_logs"],
  tags: ["event_monitoring", "notifications"]
}

-- Import the client configuration
js {
  const config = require("./client_config");
  const clientConfig = config.clientConfig;
}

-- This assertion will fail if any rows (alerts) exist in event_anomalies
SELECT
  *
FROM
  ${ref("event_check_anomalies")}
WHERE
  is_anomaly = TRUE
