config {
  type: "table",
  description: "Gets the latest partition for the GA events table",
  tags: ["event_monitoring"],
  schema: "dataform",
  database: "gtm-pz6pxlxs-owq4n"
}

-- Import the client configuration
js {
  const config = require("./client_config");
  const clientConfig = config.clientConfig;
}

WITH
latest_partition AS (
  SELECT
    '${dataform.projectConfig.vars.analytics_table}' AS source_table,
    MAX(_TABLE_SUFFIX) AS latest_partition
  FROM
    `${dataform.projectConfig.vars.dataset}.${dataform.projectConfig.vars.analytics_table}.events_${new Date().getFullYear()}*`
)
